"""
AI and Forecasting Models
==========================
AI queries, tool calls, and predictions.

These tables power:
- The AI agent's audit trail (what was asked, which model handled it)
- Forecasting (sales, demand, profit predictions)
"""

from datetime import datetime
from decimal import Decimal
from sqlalchemy import String, Numeric, DateTime, Text, ForeignKey, Integer, JSON, Index
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from app.db.base import Base
from app.models.enums import ForecastTargetType


class AIQuery(Base):
    """
    A single user query to the AI agent.
    
    Records the query, which model handled it, latency, and token usage.
    """
    __tablename__ = "ai_queries"

    id: Mapped[int] = mapped_column(primary_key=True)
    user_query: Mapped[str] = mapped_column(Text, nullable=False)
    
    # Routing decision
    intent: Mapped[str | None] = mapped_column(String(50), index=True)  # sales_query, cost_query, etc.
    model_used: Mapped[str | None] = mapped_column(String(50), index=True)  # e.g., "gemma3:4b"
    
    # Performance metrics
    latency_ms: Mapped[int | None] = mapped_column(Integer)
    tokens_in: Mapped[int | None] = mapped_column(Integer)
    tokens_out: Mapped[int | None] = mapped_column(Integer)
    cost_estimate_usd: Mapped[Decimal | None] = mapped_column(Numeric(10, 6))
    
    # Response
    response_text: Mapped[str | None] = mapped_column(Text)
    success: Mapped[bool] = mapped_column(default=True)
    error_message: Mapped[str | None] = mapped_column(Text)
    
    # Who asked
    asked_by: Mapped[int | None] = mapped_column(ForeignKey("employees.id"))
    
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), index=True)

    # Relationships
    tool_calls = relationship("AIToolCall", back_populates="query", cascade="all, delete-orphan")


class AIToolCall(Base):
    """
    A single tool invocation by the AI agent.
    
    Records what tool was called, with what arguments, and what it returned.
    """
    __tablename__ = "ai_tool_calls"

    id: Mapped[int] = mapped_column(primary_key=True)
    ai_query_id: Mapped[int] = mapped_column(ForeignKey("ai_queries.id", ondelete="CASCADE"), nullable=False, index=True)
    
    tool_name: Mapped[str] = mapped_column(String(60), nullable=False, index=True)
    arguments: Mapped[dict] = mapped_column(JSON, nullable=False)
    result: Mapped[dict | None] = mapped_column(JSON)
    
    success: Mapped[bool] = mapped_column(default=True)
    error_message: Mapped[str | None] = mapped_column(Text)
    latency_ms: Mapped[int | None] = mapped_column(Integer)
    
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    query = relationship("AIQuery", back_populates="tool_calls")


class Forecast(Base):
    """
    A prediction generated by our ML models.
    
    Examples: next week's sales, expected profit of a new lot, waste rate.
    """
    __tablename__ = "forecasts"

    id: Mapped[int] = mapped_column(primary_key=True)
    target_type: Mapped[str] = mapped_column(String(30), nullable=False, index=True)
    target_key: Mapped[str | None] = mapped_column(String(120))  # e.g., "vegetable_id=5" or "lot_code=L-001"
    
    period_start: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, index=True)
    period_end: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    
    predicted_value: Mapped[Decimal] = mapped_column(Numeric(14, 4), nullable=False)
    lower_bound: Mapped[Decimal | None] = mapped_column(Numeric(14, 4))  # Lower confidence interval
    upper_bound: Mapped[Decimal | None] = mapped_column(Numeric(14, 4))  # Upper confidence interval
    
    model_name: Mapped[str] = mapped_column(String(60), nullable=False)  # e.g., "linear_regression_v1"
    confidence: Mapped[Decimal | None] = mapped_column(Numeric(4, 3))  # 0.000 to 1.000
    
    # Features used (for explainability)
    features: Mapped[dict | None] = mapped_column(JSON)
    
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), index=True)
