"""add_locations_and_current_location_columns

Revision ID: 521f4d2c52c4
Revises: d2181b11fc97
Create Date: 2026-09-27 15:32:08.034365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '521f4d2c52c4'
down_revision: Union[str, None] = 'd2181b11fc97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
