"""make_quality_test_asset_id_nullable

Revision ID: d2181b11fc97
Revises: e06b07387540
Create Date: 2026-09-27 11:40:56.024006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2181b11fc97'
down_revision: Union[str, None] = '9b0dc8febf37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quality_tests', 'asset_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quality_tests', 'asset_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
